name: Python Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker
      - name: Build Docker image
        run: docker build -t python-app .

      # 3. Run container
      - name: Run Docker container
        run: docker run python-app